### ISSUE TITLE
All-Inclusive dictionary

### ISSUE THREAD

**Issue by eehoman** [sumantrapatnaik/WebNLG_NLP#4]
Generate a dictionary from ALL input files (.en and .vi).

May cause weird behavior?

**Comment by eehoman** [comment]
On further study, I think this is the ONLY way to go about doing this. I think that the dictionaries are used to generate the input / output encodings, so we NEED all possible input / outputs available if we don't want to see <UNK>

**Comment by PakhiAgarwal** [comment]
Great Eric!!!!!
I am trying to do some of the remaining tasks tonight. Might need your help to run the code incase of server issues. Hope we get something more better.
