### ISSUE TITLE
Removing the "_" from mTriples

### ISSUE THREAD

**Issue by eehoman** [sumantrapatnaik/WebNLG_NLP#7]
Associated with the all-inclusive dictionary file. If our network can pass these weird words through, we should find a way to turn it back into English sentences before running the BLEU classifier on it.

**Comment by eehoman** [comment]
Note that the dictionary already strips out the '_' when creating our dict files. So this will only be a change to the .vi mTriple files. It will be interesting to see if this change has any effect.

**Comment by PakhiAgarwal** [comment]
Completed with improvement in BLEU score
